# Dataset preparation for the Taiwan dataset

This notebook takes initially cleaned Taiwan dataset and prepares train and test datasets

**Author:** Ben Flint  
**Date:** 01/09/2026  
**Input:** taiwan_default_data_vx.x.csv from 00_EDA_Taiwan_dataset.ipynb
**Output:** train and test datasets ready for 03_champion_logistic.ipynb

In [15]:

import pandas as pd
from config import ID_VARIABLE, TARGET_VARIABLE
from sklearn.model_selection import train_test_split

In [16]:
rds = pd.read_csv('../data/processed/taiwan_default_data_v0.1.csv')
y = rds[TARGET_VARIABLE]
X = rds.drop([TARGET_VARIABLE, ID_VARIABLE], axis='columns')
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state = 42, stratify=y)

In [17]:
X_train.describe()

,X01_LIMIT_BAL,X02_SEX,X03_EDUCATION,X04_MARRIAGE,X05_AGE,X06_PAY_0,X07_PAY_2,X08_PAY_3,X09_PAY_4,X10_PAY_5,X11_PAY_6,X12_BILL_AMT1,X13_BILL_AMT2,X14_BILL_AMT3,X15_BILL_AMT4,X16_BILL_AMT5,X17_BILL_AMT6,X18_PAY_AMT1,X19_PAY_AMT2,X20_PAY_AMT3,X21_PAY_AMT4,X22_PAY_AMT5,X23_PAY_AMT6
count,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.00000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,2.400000e+04,24000.000000,24000.000000,24000.000000,24000.000000
mean,167364.666667,1.604750,1.842500,1.560708,35.432625,-0.014125,-0.134083,-0.166917,-0.221333,-0.270333,-0.293333,51100.50225,49012.267583,46861.880083,43156.661458,40164.412625,38675.979875,5623.556292,5.879975e+03,5215.777583,4790.331833,4769.941750,5229.905500
std,129511.313151,0.488915,0.744625,0.528513,9.195256,1.123155,1.198818,1.194166,1.161924,1.125192,1.145467,73510.03206,70840.102410,68403.933692,64046.730878,60627.850612,59308.737828,16148.316646,2.025298e+04,17513.554475,15060.693585,15048.470405,17850.346975
min,10000.000000,1.000000,1.000000,1.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-165580.00000,-69777.000000,-61506.000000,-81334.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3513.75000,2989.750000,2652.000000,2332.000000,1746.000000,1225.000000,1000.000000,8.400000e+02,390.000000,291.000000,246.000000,100.000000
50%,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22330.00000,21107.000000,20031.000000,19004.500000,18102.500000,16993.000000,2100.500000,2.014000e+03,1805.500000,1500.000000,1500.000000,1500.000000
75%,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,66966.50000,63992.750000,60033.750000,54386.500000,50142.250000,48977.250000,5018.250000,5.000000e+03,4580.500000,4015.250000,4040.000000,4000.000000
max,1000000.000000,2.000000,4.000000,4.000000,75.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,964511.00000,983931.000000,855086.000000,891586.000000,927171.000000,961664.000000,873552.000000,1.215471e+06,896040.000000,621000.000000,426529.000000,528666.000000

In [18]:
X_test.describe()

,X01_LIMIT_BAL,X02_SEX,X03_EDUCATION,X04_MARRIAGE,X05_AGE,X06_PAY_0,X07_PAY_2,X08_PAY_3,X09_PAY_4,X10_PAY_5,X11_PAY_6,X12_BILL_AMT1,X13_BILL_AMT2,X14_BILL_AMT3,X15_BILL_AMT4,X16_BILL_AMT5,X17_BILL_AMT6,X18_PAY_AMT1,X19_PAY_AMT2,X20_PAY_AMT3,X21_PAY_AMT4,X22_PAY_AMT5,X23_PAY_AMT6
count,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6.000000e+03,6000.000000,6000.000000,6000.000000,6000.000000,6.000000e+03,6000.000000,6000.000000,6000.000000,6000.000000
mean,167962.946667,1.599667,1.841333,1.552500,35.697000,-0.027000,-0.132500,-0.163333,-0.218000,-0.249667,-0.282167,51714.645500,49846.305500,4.761825e+04,43688.099000,40899.354333,39654.882500,5823.677333,6.085918e+03,5265.297167,4969.057000,4917.171167,5157.890833
std,130698.538357,0.490007,0.744032,0.526267,9.305713,1.126417,1.190734,1.207711,1.197657,1.164571,1.167951,74141.161902,72495.226802,7.301167e+04,65468.536253,61471.293451,60524.310508,18128.961193,3.184007e+04,17977.164797,17884.895787,16165.776457,17484.253835
min,10000.000000,1.000000,1.000000,1.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-14386.000000,-18618.000000,-1.572640e+05,-170000.000000,-53007.000000,-150953.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3699.000000,2965.000000,2.731000e+03,2302.500000,1885.000000,1368.500000,934.750000,7.920000e+02,391.000000,300.000000,279.750000,189.000000
50%,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22560.000000,21533.500000,2.030800e+04,19201.500000,18144.500000,17339.500000,2100.000000,2.000000e+03,1800.000000,1500.000000,1500.000000,1500.000000
75%,240000.000000,2.000000,2.000000,2.000000,42.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,67723.750000,64126.750000,6.038625e+04,54859.000000,50480.500000,49883.750000,5000.000000,5.000000e+03,4366.250000,4003.250000,4021.250000,4122.250000
max,800000.000000,2.000000,4.000000,4.000000,79.000000,8.000000,7.000000,8.000000,8.000000,7.000000,8.000000,653062.000000,671563.000000,1.664089e+06,706864.000000,514114.000000,499100.000000,493358.000000,1.684259e+06,417588.000000,528897.000000,379267.000000,443001.000000

In [19]:
y_train.describe()

count    24000.000000
mean         0.221208
std          0.415069
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Y_DEF_FLAG_1M, dtype: float64

In [20]:
y_test.describe()

count    6000.000000
mean        0.221167
std         0.415067
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: Y_DEF_FLAG_1M, dtype: float64

In [ ]:
for dataset, name in zip([X_train, X_test, y_train, y_test], ['X_train', 'X_test', 'y_train', 'y_test'], strict=True):
    dataset.to_csv(f"../data/processed/basic_data_prep/{name}.csv", index=False)